steps:
  # Bouw de Docker-image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/github-w2/staging-app", "."]
  
  # Push de Docker-image naar GCR
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/github-w2/staging-app"]


- name: "google/cloud-sdk:latest"
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    TIMESTAMP=$(date '+%Y%m%d%H%M%S')
    gcloud deploy releases create "app-release-dev-$TIMESTAMP" --delivery-pipeline=gke-pipeline-dev --region=us-central1 --from-k8s-manifest=./appK8.yaml

options:
  logging: CLOUD_LOGGING_ONLY
