steps:
  # Bouw de Docker-image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/github-w2/staging-app:$COMMIT_SHA", "."]
  
  # Push de Docker-image naar GCR
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/github-w2/staging-app:$COMMIT_SHA"]


- name: "google/cloud-sdk:latest"
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=staging-pipeline --region=us-central1 --from-k8s-manifest=./appK8.yaml

options:
  logging: CLOUD_LOGGING_ONLY