steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/github-w2/gke-repo/custom-cicd-staging-build", "."]
  id: 'Build Docker Image'

  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/github-w2/gke-repo/custom-cicd-staging-build"]
  id: 'Push Docker Image'
  
  # deploy container image to GKE
- name: "google/cloud-sdk:latest"
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=staging-pipeline --region=us-central1 --from-k8s-manifest=./appK8.yaml

options:
  logging: CLOUD_LOGGING_ONLY