steps:
  # Bouw de Docker-image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/github-w2/my-app:$COMMIT_SHA", "."]
  
  # Push de Docker-image naar GCR
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/github-w2/my-app:$COMMIT_SHA"]

  # Implementeer de nieuwe Docker-image met de staging-pipeline
- name: "gcr.io/cloud-builders/gcloud"
  args: ["deploy", "my-app-staging", "--image=gcr.io/github-w2/my-app:$COMMIT_SHA", "--delivery-pipeline=staging-pipeline"]

options:
  logging: CLOUD_LOGGING_ONLY